spring:
  application:
    name: genie_tune_java
  # local 개발용 import
  config:
    import: "optional:classpath:secret/secret.yml"
  # 자동 생성해주는 것들 제외하는 것
  autoconfigure:
    exclude:
      # Spring Security에서 기본 유저 생성 제외
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  # docker- 배포용 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  graphql:
    schema:
      locations: classpath:graphql/**/
    http:
      path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.security.authorization: DEBUG
    org.springframework.security.web.access.intercept.AuthorizationFilter: DEBUG
    org.springframework.security.web.access.ExceptionTranslationFilter: DEBUG
    org.springframework.boot.web.servlet.error: DEBUG
    org.springframework.graphql: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG

server:
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always




jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}

nts:
  api:
    key: ${NTS_API_KEY}

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_URL}